keys:
  # Personal yubikeys
  - &samiarda
    - &keychain 0BE1 FA6C 1618 6B35 B550  B1E6 1C30 B1CE E9AC F97D
    - &backup   3964 72B3 FDE2 8A91 8B6A  6486 B841 D3FC 609A B98B
  # Converted ssh host keys
  - &hosts
    # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &srv-prod-1 age103zyxp0qku4dyqslmgx370jv8yttc6wzhfhlfyd3mq7369cgje6stplz5u
creation_rules:
  - path_regex: secrets/creds/shared.ya?ml$
    key_groups:
      - age:
          - *srv-prod-1
        pgp:
          - *keychain
          - *backup
  - path_regex: secrets/creds/srv-prod-1.ya?ml$
    key_groups:
      - age:
          - *srv-prod-1
        pgp:
          - *keychain
          - *backup