keys:
  # Personal yubikeys
  - &samiarda
    - &keychain 00209B52F8A651F4CAD8385C419C4F9E21E8F900
    - &backup  E95FDF6DDC6967B7B317F23DE92236CA94126BC6
  - &hosts
    #- &host age123abc456
    - &srv-prod-1 age1rnla47cacaz9zcvaqtz7y7t58wjfrr2a9mzfsplsfm9rpw75mexsv4was9
creation_rules:
  - path_regex: secrets/public/shared.ya?ml$
    key_groups:
      - pgp:
        - *keychain
        - *backup
  - path_regex: secrets/public/srv-prod-1.ya?ml$
    key_groups:
      - age:
          - *srv-prod-1
        pgp:
          - *keychain
          - *backup